version: '3'

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - git_data:/data
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      - WORDPRESS_DB_HOST=wpdb:3306
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wppass
      - WORDPRESS_DB_NAME=wpdb
    depends_on:
      - wpdb

  wpdb:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=wpdb
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wppass
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - wp_db_data:/var/lib/mysql

volumes:
  db_data:
  git_data:
  wp_db_data:

